### ISSUE TITLE
Add to homebrew casks

### ISSUE THREAD

**Issue by gbaranski** [ObuchiYuki/DevToysMac#24]

**Comment by dotWee** [comment]
This is a basic working cask formula that serves the current release V0.0.6: 

It can be tested by installing it from my [testing tap](https://github.com/dotWee/homebrew-repo/blob/main/Casks/devtoysmac.rb): `brew install dotwee/repo/devtoysmac`

```ruby
cask "devtoysmac" do
  version "V0.0.6"
  sha256 "1770202ee4cb3bc45f2100992dceb308f606b130529d70d71abff1e11ad76f28"

  url "https://github.com/ObuchiYuki/DevToysMac/releases/download/0.0.6/DevToys.zip"
  name "DevToysMac"
  desc "This is the mac app version of Windows DevToys!"
  homepage "https://github.com/ObuchiYuki/DevToysMac"

  app "DevToys.app"

  zap trash: [
    "~/Library/Preferences/com.yuki.DevToys.plist",
  ]
end
```

Since I'm not the maintainer and do not actively follow the development, I won't create a pull request for merging into the public main repo.

Some resources for the maintainer @ObuchiYuki:

- [Cask Cookbook](https://docs.brew.sh/Cask-Cookbook)
- [Using `brew create URL` to create a basic formula](https://docs.brew.sh/Manpage#create-options-url)

Less relevant:

- [How to Create and Maintain a Tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap) (some like to maintain a extra tap to work around dealing with the main repo)

**Comment by ObuchiYuki** [comment]
@gbaranski  @dotWee Thank you for your issue!
I also want to introduce homebrew cask to this project. I'll check the resources. Thank you again!

**Comment by dotWee** [comment]
No problems. Thanks for your work! I really enjoy your application.

Also, you may want to check out [Sparkle](https://github.com/sparkle-project/Sparkle), a well known framework for (self) updating macOS applications outside of the App Store.

**Comment by SeanSith** [comment]
https://github.com/Homebrew/homebrew-cask/pull/119273 has been submitted.

**Comment by mheob** [comment]
I can confirm this. You can install the tool with this command:

```sh
brew install --cask devtoys
```

Thanks @SeanSith

**Comment by gbaranski** [comment]
thanks,

closed by https://github.com/Homebrew/homebrew-cask/pull/119273

**Comment by ObuchiYuki** [comment]
@dotWee @gbaranski @SeanSith @mheob 

Thank you so much for your support for brew! I don't have much knowledge of brew and this cooperation really helped me!
