### ISSUE TITLE
Double quote gets transformed.

### ISSUE THREAD

**Issue by jacola** [ObuchiYuki/DevToysMac#45]
Copy and paste works fine, but when typing double quotes into the JSON formatter, macOS transforms them to /slanted/ quotes.

`{ "test": "darn" }` becomes `{ “test”: “darn” }` resulting in invalid JSON.

![image](https://user-images.githubusercontent.com/941214/154203440-72c60c29-cb06-4803-ac49-4704e2284885.png)

**Comment by DanielSouzaBertoldi** [comment]
I dug a deep into this problem and to me (unexperienced Swift developer) it _seems_ that the problem is the [Smart Quotes feature](https://developer.apple.com/forums/thread/124410?answerId=388845022#388845022) that Mac has enabled by default. Disabling it in the System Preferences fixes this issue.

I tried to code something to fix this without needing to disable the Smart Quotes feature, but ran into a few problems:

There's a flag that can be used to disable this behavior programmatically, called [`isAutomaticQuoteSubstitutionEnabled`](https://developer.apple.com/documentation/appkit/nstextview/1449258-isautomaticquotesubstitutionenab) but it's only available for the `NSTextView` view. Since the `textView` attribute of the `TextViewSectionBase` is actually of type `NSView` we can't directly access it (At least I think we can't, I tried a few things and got nowhere), nor convert it to a `NSTextView`.

One thing that worked was to use the `replaceOccurrences` function, but I didn't create a PR since to me seems kinda ugly to use it for this problem, and I don't know if there's another way to do it. The code ended up like:

```swift
    var string = "" {
        didSet {
            // using two replacingOccurrences since both quotes have actually different from one another
            self.textView.string = string.replacingOccurrences(of: "“", with: "\"").replacingOccurrences(of: "”", with: "\"")
            self.copyButton.stringContent = string
        }
    }
```

If anyone got any ideias on how to solve this problem more elegantly, let me know, I'll gladly create the PR fixing this 😄

**Comment by jacola** [comment]
I have standard keyboard settings as well for an English OS in Japanese region. 
![Screen Shot 2022-02-17 at 11 24 47](https://user-images.githubusercontent.com/941214/154392594-03d85111-d765-4937-8b7a-594b26b30b10.png)

**Comment by ObuchiYuki** [comment]
@jacola @DanielSouzaBertoldi 

I was able to reproduce and fix the bug. Thanks for your help!

![タイトルなし](https://user-images.githubusercontent.com/20896810/154781694-77782d0a-16c4-4538-941d-17c011bab8af.gif)

**Comment by ObuchiYuki** [comment]
@DanielSouzaBertoldi @jacola Thank you for your support! I can fix this bug!

You can get fixed version on 
https://github.com/ObuchiYuki/DevToysMac/releases/tag/0.0.8.2
